# Generated by Django 2.0.7 on 2018-07-20 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comment_time',
            new_name='comment_time',
        ),
    ]
